/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Message: typeof import('./src/components/Message.vue')['default']
    TheCount: typeof import('./src/components/TheCount.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
  }
}
